// The whole way in, one screen at a time.
import { chromium } from 'playwright'
const OUT='/tmp/claude-0/-home-claude/9e4f1146-1d92-5690-b689-30dcc0c1e170/scratchpad'
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--no-sandbox','--disable-dev-shm-usage']})
const page=await b.newPage({viewport:{width:430,height:920},deviceScaleFactor:2})
const errs=[];page.on('pageerror',e=>errs.push(e.message))
await page.goto('http://localhost:4173/',{waitUntil:'networkidle'})
await page.fill('input[type=text]','Newbie'); await page.fill('input[type=password]','1234')
await page.locator('button',{hasText:'Begin the Journey'}).click()
await page.waitForSelector('text=Who are you?',{timeout:10000})
await page.waitForTimeout(700)
await page.screenshot({path:`${OUT}/ob-1-face.png`})
await page.locator('button',{hasText:/^This is me/}).click()
await page.waitForSelector("text=My Wizard",{timeout:10000})
await page.waitForTimeout(900)
await page.screenshot({path:`${OUT}/ob-2-look.png`,fullPage:true})
await page.locator('button',{hasText:/^That's me!/}).click()
await page.waitForSelector('text=Choose your Nest',{timeout:10000})
await page.waitForTimeout(700)
await page.locator('button',{hasText:'Sea Eagles'}).first().click()
await page.locator('button',{hasText:/^Join the /}).click()
await page.waitForSelector('text=What shall we practise',{timeout:10000})
await page.waitForTimeout(600)
await page.screenshot({path:`${OUT}/ob-3-practice.png`})
await page.locator('button',{hasText:/Multiplication/}).click()
await page.waitForTimeout(300)
await page.screenshot({path:`${OUT}/ob-3b-practice.png`})
await page.locator('button',{hasText:/^Onward ✦$/}).click()
await page.waitForSelector('text=Let the castle take your measure',{timeout:10000})
await page.waitForTimeout(800)
await page.screenshot({path:`${OUT}/ob-4-invite.png`,fullPage:true})
console.log('errors:',errs.length?errs.join('|'):'none')
await b.close()
